name: CI

on:
  pull_request:

  push:
    branches: [main]

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Rubocop
      run: |
        gem install bundler
        bundle config set without 'development test'
        bundle config set with 'lint'
        bundle install
        bundle exec rubocop --format progress

  build:
    needs: [linting]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev

    - name: Build
      run: |
        sudo apt-get install libcurl4-openssl-dev
        gem install bundler -v '<2'
        bundle install --jobs 4 --retry 3

    - name: Test
      run: |
        bundle exec rake
